const ADD_POST = 'ADD_POST';
const DELETE_POST = 'DELETE_POST';
const SHOW_POST = 'SHOW_POST';
const EDIT_POST = 'EDIT_POST';
const UPDATE_POST = 'UPDATE_POST';

export  {ADD_POST,DELETE_POST,EDIT_POST,UPDATE_POST,SHOW_POST};
